apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: errander-prometheus
    url: http://localhost:9091
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: GET
